// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
/*
HERES THE DEAL. HERE IS A ROUGH TODO-LIST TO BRING MY GAME TO COMPLETION

U_I_:
BRIEFS SHOULD HAVE 2 SPRITES PER TYPE- A NORMAL COLOR MATCHING SPRITE, AND THAT SPRITE WITH A PLUS IN THE TOP RIGHT CORNER WHEN THERE ARE UPGRADES TO BE WON.
CREATE RANK UP CUTSCENE(?) VISUALS.
CUTSCENES
UNIFY ALL OF THE DISPLAY TEXTS FOR ALL THE PLACES WITH VENITE LARGE (MEDIUM NEW ONE) AND WHITE.
ADD A DRILL WRHIRRING NOISE WHEN UPGRADING SYSTEMS
UPDATE HUD WITH RELEVENT INFO, INCLUDING LEVEL SPECIFIC AND AI COMMENTS
GARAGE CHANGES, DRAG AND DROP FIX AND UPGRADE RECEPTACLE, PASSIVES REPRESENTATIONS, RIGHT CLICK UPGRADES
ADD CUTSNENE ON LEVEL COMPLETION. SHIP FLYING AWAY?...


M_E_C_H_A_N_I_C_S_:
FINAL BOSS
"R" SHOULDN'T RESET THE GAME. ESC SHOULD TOGGLE MENU OPTIONS. BACK TO START, RESTART, SAVE, STATS, CONTROLS, ETC.
ENEMY SCANNER RANGE SHOULD INCREASE THE LONGER A BATTLE GOES
HP HEALING 
RELOADING SHOULD BE R, SHOULD HAVE ICONS ON THE HUD FOR REMAINING AMMO AND COOLDOWN. 

A_R_C_H_I_T_E_C_T_U_R_E_:
MAYBE WHAT WE DO IS THIS- THERE ARE 4-5 SHIP CLASSES, WITH 3-6 SHIPS PER CLASS. SEVERAL POSSIBLE PASSIVE SETS, LETS SAY 10, BUT THEY ARE FAIRLY CLOSE TO EACH OTHER SO THAT THE SHIPS DON'T VARY TOO WILDLY
SHIPS HAVE AN UPGRADE POINT LIMIT. LIMIT DEPENDS ON CLASS. CLASS SET BY RANK UNLOCKED AT.
EACH UPGRADE HAS ASSIGNED UPGRADE POINTS.
EACH SYSTEM SLOT HAS A MAX POINT VALUE
THERE ARE 4-5 SHIP CLASSES, WITH 3-6 SHIPS PER CLASS. SEVERAL POSSIBLE PASSIVE SETS, LETS SAY 10, BUT THEY ARE FAIRLY CLOSE TO EACH OTHER SO THAT THE SHIPS DON'T VARY TOO WILDLY
SHIPS HAVE AN UPGRADE POINT LIMIT. LIMIT DEPENDS ON CLASS. CLASS SET BY RANK UNLOCKED AT.

CREATING ALL LEVEL TYPES
ENEMY TYPES
NOT ALL LEVELS CAN HAVE ASTEROIDS- END GAME EVERY EVEL TYPE CAN HAVE THEM, EARLY ONLY A FEW AND TEH ASTEROIDS ARE LESS. MORE POINTS FOR ROID LEVELS
EACH LEVELTYPE OBJ HAS LOGIC FOR IF ASTEROIDS IS TRUE ON CURRENT LEVEL, IN WHICH CASE CREATE SYSTEM TO RANDOMLY PLACE THEM.



STEALTH MISSION, COMPLETE WITH LIMITED # OF KILLS, PERHAPS EVEN DETECTION. 
COMPLETING SOME MISSIONS WITHOUT POINT REWARDS?



LEVE TYPE IDEAS: 
Timed challenge, destroy objects within time frame. No enemies neccesarily, at least at the lower levels. 
Points are awareded based on speed.

Specific targets- Pretty much the exact same as hunt mission, but have new enemy type. Faster, strong, and maybe they run away if you are 
in close range? they want to fire from a distance, so they close on you then run as you shoot as them.
Everytime you kill one set global var to ++, once it reaches mission requirements then we are done. 

Recon, scout and document areas without being discovered.



Mission type: Timed kill challenge
	diffuclty scaling time
	difficulty scaling enemy weapons and armor
	difficulty scaling enemy quantity?
	
 I should probably only have 8 rooms per planet, or however many level types there are. these can be easily re-used per level once i procedurally generate enemies and other objects.