// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
/*
HERES THE DEAL. HERE IS A ROUGH TODO-LIST TO BRING MY GAME TO MVP
 
 
 Firing range, the degree to which A SHIP CAN SHOOT is SHIP CLASS SPECIFIC
 

FOR PAYLOAD- MINES. THEY SIT ALL OVER THE MAP, AND WHEN YOU TRIGGER THEM THEY CHANGE COLOR (MAYBE ARMS POP OUT OR SOMETHING?)
DETECTION RANGE VARIES ON TYPE- THERE IS EMP AND KINETIC. EMP MINES ARE WAY FASTER, BUT A MUCH LOWER DETECTION RANGE. 
KINETIC MINES HAVE HUGE DETECTION RANGE BUT AREN'T THAT FAST.
BOTH CAN IMPACT AGAINST ANYTHING, INCLUDING PLAYER FIRE. THEY BREAK ON CONTACT WITH ASTEROIDS SHIPS ETC.
GIANT ASTEROIDS- ONLY A FEW, MOVING AT SLIGHT DEGREE ACROSS THE MAP. THEY SOAK EVERYTHING. 
ONE OR 2 ENEMY DESTROYERS, KITTED LIKE THE FRIGATE, EXCECPT THEY ARE JUST MOVING ACROSS THE SCREEN. AN OBSTACLE TO BE NAVIGATED NOT DESTROYED, NO PARTICLE BEAM
5 PARTICLE BEAMS FIRING DOWN THE "TUNNEL" AT RANDOM INTERVELS. NOT TRACKING JUST RANDOM. KILLS MINES, ASTEROIDS (NOT BIG ONES THEY STOP IT).
THEY WON'T FIRE IN ALLY FRIGATE IS IN THE WAY. 
SMALL ASTEROIDS AS WELL
A FEW "QUEENS" THEY HUNT YOU HARD, DODGE OBSTACLES AND ARE REALLY REALLY HARD TO KILL. DIE TO PARTICLE BEAMS. 
A TIMER, THIS IS SET IN THE LEVEL CONFIG. WRITE A LITTLE FUNCTION THAT COUNTS STEPS, AND EVERY 30 STEPS RESETS A NUMBER AND REMOVES 1 TOFROM  THE TIMER
THIS IS HOW I WILL SIMULATE SECONDS COUNT DOWN. 
BOOST STATIONS. 1 CHARGE- WHEN PLAYER COLLIDES WITH IT, RESET THEIR BOOST, SHIELDS, THEN IT "DIES". 
THESE STATIONS ARE SURROUNDED BY AN AURA THAT DISSAPEARS. 
ONCE WITHIN RANGE, GREEN ALERT MID SCREEN LKE OTHER WARNINGS, THEN YOU CAN FIRE. ONCE IT MAKES CONTACT, LEVEL ENDS. 


 
ALSO ADD A WARNING IN YELLOW FOR INCOMING PARTICLE BEAM DURING THE DELAY BETWEEN LASER AND FIRING?
 
 
MORE CONSIDERATIONS. LOCK IN A PLANET PER RANK? PLANET BASED ENVIORNMENT VARIABLES
ONLY MARS HAS ASTEROIDS, VENUS HAS OLD SPACE HULKS, EARTH HAS LONG RANGE PARTICLE CANNONS MAYBE, THEY CAN BE DESTROYED?
 
BREIFING RIGHT CLICK SHOULD BE EITHER ANOTHER ROOM, OR AT LEAST A HUGE MODAL. IT SHOULD BE FULL
OF ALL THE LEVEL INFORMATION, WHAT TO EXPECT ETC.
 
 
ADD MORE UPGRADES!
WE START WITH 4 SHIP CLASSES, AND 1 SHIP FOR EACH. THAT MEANS ONE NEW SHIP WITHA  NEW CLASS
3 UNIQUE PASSIVE SETS FOR EACH CLASS, ALL PRETTY CLOSE TO EACH OTHER BUT UNIQUE FROM OTHER CLASSES. 
CREATING 5 NEW LEVEL TYPES
ENEMY TYPES ADD AT LEAST 3 MORE
 
FINAL BOSS
 
  
ONSIDER ACTIVATEABLE BOMBS AND MISSILES. FIRST RIGHT CLICK FIRES, SECOND EXPLODES

OOH! EMP WEAPON! SECONDARY WITH LARGE SPREAD, SETS ALARM WHICH SKIPS STEP EVENTS ON ENEMIES UNTIL IT WEARS OFF. 
ION CALTROPS- CHANGE RIGHTCLICK LOGIC WHEN GLOBAL.SELECTEDSHIP.SECONDARYWEAPON.NAME CONTAINS CALTROPS. THESE
CALTROPS WILL DROP THE SECONDARYWEAPON.CAPACITY # OF OBJ_SECONDARYWEAPONCALTROPS. THESE ARE SMALL IN SIZE LARGE IN HIT BOX, ON IMPACT
CALTROPS WILL EITHER ION STUN OR DO DAMAGE. SET ENEMY ATTRIBUTES SO THAT IF THE NAME CONTAINS ION, THERE IS A LOOP WICH TAKES THE ION DAMAGE (SIMILAR TO HOW ION DAMAGE WORKS NOW)
EXCEPT THAT INSTEAD OF STOPPING THEM I THEIR TRACKS, IT JUST EATS UP THEIR ATTACK SPEED AND MOVE SPEED. SHOULD BE DOABLE FAIRLY EASILY, ACTUALLY! IT JUST HAS TO RESET AFTER THE ION DAMAGE 
IS DONE. THAT PART MIGHT BE TRICKY.
 