// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
/*
HERES THE DEAL. HERE IS A ROUGH TODO-LIST TO BRING MY GAME TO COMPLETION

MINI MAP //DONE
SENSORS //DONE
SMOOTH TURNING, REVERSE ANIMATION. TURN RADIUS //DONE
SAVING //DONE
RIGHT CLICK DESCRIBE EVENTS ON SHOP AND GARAGE //DONE
UPGRADE PURCHASING //DONE
SHIP UPGRADING //DONE
MISSION TREES //DONE
PLANET BASED MISSIONS //DONE
ADD A MANILLA FOLDER THING FOR MISSION BRIEFS. SELECTING THE BRIEF WILL SET THE CORRENT INDICES //DONE
CHOOSING MISSIONS// DONE

PLANET SELECTION
CUTSCENES
CONSIDER OPENING CAMERA OBJECT TO INCREASE FOV
CREATING ALL LEVELS
ENEMY TYPES
ENEMY AI
TYPES OF MISSIONS- CONTRACT, SURVIVAL, ESCAPE, OBJECTIVES?
FINAL BOSS
ADD AN ANIMATION TO THE SHOP, WHERE WHENEVER YOU SELECT A NEW SYSTEM, 
HYDROLIC DOORS OPEN, AND IF YOU RESELCT THEY CLOSE THEN OPEN AGAIN
ADD A DRILL WRHIRRING NOISE WHEN UPGRADING SYSTEMS
CONSIDER A SYSTEM WHERE SHIELDS REFRESH, BUT HP DOESN'T REPAIRS ARE REQURIED. POSSIBLY ENGINE BURNOUT, ENERGY CELLS ETC.
