// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
/*
HERES THE DEAL. HERE IS A ROUGH TODO-LIST TO BRING MY GAME TO COMPLETION

MINI MAP //DONE
SENSORS //DONE
SMOOTH TURNING, REVERSE ANIMATION. TURN RADIUS //DONE
SAVING //DONE
RIGHT CLICK DESCRIBE EVENTS ON SHOP AND GARAGE //DONE
UPGRADE PURCHASING //DONE
SHIP UPGRADING //DONE
MISSION TREES //DONE
PLANET BASED MISSIONS //DONE
ADD A MANILLA FOLDER THING FOR MISSION BRIEFS. SELECTING THE BRIEF WILL SET THE CORRENT INDICES //DONE
CHOOSING MISSIONS// DONE
HYDROLIC SHOP DOORS OPEN, AND IF YOU RESELCT THEY CLOSE THEN OPEN AGAIN//DONE
IMPLEMENT COMMENDATIONS UI //DONE
TYPES OF MISSIONS- ARCHITECTURE //DONE
ADD BACK POINTS TO SHOP //DONE
MIGRATE SYSTEM UPGRADE STATUS FIELDS TO NEW ARRAY //DONE
REMOVE NON BASIC UPGRADES ON DEATH //DONE
PLANET SELECTION //DONE


U_I_:
BRIEFS SHOULD HAVE 2 SPRITES PER TYPE- A NORMAL COLOR MATCHING SPRITE, AND THAT SPRITE WITH A PLUS IN THE TOP RIGHT CORNER WHEN THERE ARE UPGRADES TO BE WON.
CREATE RANK UP CUTSVENE(?) VISUALS.
REFACTOR GAMECONTROLLER GUI FOR NEW LEVELTYPES AND SUCH
CUTSCENES
UNIFY ALL OF THE DISPLAY TEXTS FOR ALL THE PLACES WITH VENITE LARGE (MEDIUM NEW ONE) AND WHITE.
ADD A DRILL WRHIRRING NOISE WHEN UPGRADING SYSTEMS
CREATE HUD THAT IS ACTIVE DURING MISSIONS- ENCOMPASSES ALL THE EDGES OF THE SCREEN.
UPDATE GALAXY BUTTON
RIGHT CICK PLANET INFO, CONFIRMATION SCREENS, AND HOVERING PLANET NAME TEXT. 


M_E_C_H_A_N_I_C_S_:
ENEMY AI
FINAL BOSS
CONSIDER A SYSTEM WHERE SHIELDS REFRESH, BUT HP DOESN'T REPAIRS ARE REQURIED. POSSIBLY ENGINE BURNOUT, ENERGY CELLS ETC.
FORCE BRIEF SELECTION ATER PLANET CHANGE, ENFORCED WITH GRAYED OUT HANGAR BUTTON AND IMPERATOR CHAT.
ENEMIES SHOULD SPAWN RANDOMLY


A_R_C_H_I_T_E_C_T_U_R_E_:
CONSIDER OPENING CAMERA OBJECT TO INCREASE FOV
CREATING ALL LEVEL TYPES
ENEMY TYPES
ADD LOCKED PLANET SYSTEM AND SPRITES


STEALTH MISSION, COMPLETE WITH LIMITED # OF KILLS, PERHAPS EVEN DETECTION. 
COMPLWTING SOME MISSIONS WITHOUT POINT REWARDS?

CLOAKING? PASSIVE ON SHIP, REDUCES ENEMY DETECTION RANGE 9ALL SHIPS HAVE, DETECTION TAKES THIS INTO ACCT.
EVASION PASSIVE, EFFECTS % HIT. 
EXPERIENCED CREW PASSIVE, REDUCE RELOAD TIME
HOTSHOT CREW PASSIVE IMPROVES ACCURACY
FOV PASSIVE????




levels have points awarded, possible unlocks, and commendations. Required commendations for level up, once your surpass them, its a different bridge cutscene maybe. 
Points awarded tie to difficulty of the mission- maybe have a difficulty rating as well? stars, perhaps? Missions with unlocks typically provide very few to no point bonuses,
and have higher than average commendations so you have to choose.
I think i DEFINITELY want hp to stick with the ship, And you have to choose to repair it from the garage. 



