hp = 1 * GetDifficultyRankModifier();
depth = -2
parent_frigate = other;
shotsFired = 0
shootAngle = 360; 
primaryDelay = 0;
fireRate = 30 * GetDifficultyRankModifier();
cooldownTimer = 0;
cooldownDuration = 5;
capacity = 5 * GetDifficultyRankModifier();