image_index = 0;
 depth = -3
priming = false;
firing = false;
beginFiringSequence = false;
shootAngle = 360; 
primaryDelay = 0;
cooldownTimer = 0;
cooldownDuration = 5;
capacity = 50;
alarm[0] = irandom_range(0, 1000);